### ISSUE TITLE
[Bug]: Plugin "obsidian-reminder-plugin" is not passing Component in renderMarkdown

### ISSUE THREAD

**Issue by pravin-d** [uphy/obsidian-reminder#165]
### Describe the bug

Getting the following error in console

app.js:1 Error: Plugin "obsidian-reminder-plugin" is not passing Component in renderMarkdown. This is needed to avoid memory leaks when embedded contents register global event handlers.
    at t.render (app.js:1:1231191)
    at t.renderMarkdown (app.js:1:1230972)
    at eval (plugin:obsidian-reminder-plugin:15229:39)
    at flush (plugin:obsidian-reminder-plugin:14593:9)
    at init (plugin:obsidian-reminder-plugin:14741:5)
    at new Reminder2 (plugin:obsidian-reminder-plugin:16375:5)
    at NotificationModal.onOpen (plugin:obsidian-reminder-plugin:16458:5)
    at e.open (app.js:1:1309979)
    at ReminderModal.showBuiltinReminder (plugin:obsidian-reminder-plugin:16432:113)
    at ReminderModal.show (plugin:obsidian-reminder-plugin:16398:12)

### Steps to reproduce

Not sure

### Operating system

macOS

**Comment by offbrands-studio** [comment]
got this same error today.
